CREATE TABLE DEPARTMENTS(
	DEPARTMENT_PK VARCHAR(20) NOT NULL,
	DEPARTMENT_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (DEPARTMENT_PK)
);
CREATE TABLE EMPLOYEES(
	EMPLOYEE_PK VARCHAR(20) NOT NULL,
	DEPARTMENT_FK VARCHAR(20) NOT NULL,
	EMPLOYEE_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (EMPLOYEE_PK),
	FOREIGN KEY (DEPARTMENT_FK) REFERENCES DEPARTMENTS(DEPARTMENT_PK)
);
CREATE TABLE COMMUTES (
	COMMUTE_PK VARCHAR(20) NOT NULL,
	COMMUTE_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (COMMUTE_PK)
);
CREATE TABLE ATTENDS(
    ATTEND_PK INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_FK VARCHAR(20) NOT NULL,
    COMMUTE_FK VARCHAR(20) NOT NULL,
    WORKDATE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ATTEND_PK),
    FOREIGN KEY (EMPLOYEE_FK) REFERENCES EMPLOYEES(EMPLOYEE_PK),
    FOREIGN KEY (COMMUTE_FK) REFERENCES COMMUTES(COMMUTE_PK)
);